### ISSUE TITLE
Use completing-read in interactive prompts

### ISSUE THREAD

**Issue by furkanusta** [Dspil/typing-categories#2]
Using
```emacs-lisp
(interactive (list (completing-read "Enter category to delete: " (text-categories-list))))
```
instead of 
```emacs-lisp
(interactive "sEnter category: ")
```

gives a better interface in many cases, especially for change and delete

Would you be interested in this? I can send a PR

**Comment by Dspil** [comment]
It is a nice idea. I will implement it for the storing of a category too. Thank you!

**Comment by Dspil** [comment]
I made this change in the last commit. When the command requires the category to exist, the match is also required. In all other cases, there is a completion list but you can enter whatever you want. Thank you again for the suggestion!

**Comment by furkanusta** [comment]
Thanks for the quick update. exact match makes sense
